"""create tables 1

Revision ID: 05b2b099a6b3
Revises: 32eda944c957
Create Date: 2020-11-03 19:50:41.076968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b2b099a6b3'
down_revision = '32eda944c957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
