"""create tables

Revision ID: 32eda944c957
Revises: 3463e0bb3b7f
Create Date: 2020-11-03 19:45:02.094463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32eda944c957'
down_revision = '3463e0bb3b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
