"""change spot model

Revision ID: 3463e0bb3b7f
Revises: c2e4a6d3913c
Create Date: 2020-11-03 19:20:21.065632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3463e0bb3b7f'
down_revision = 'c2e4a6d3913c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
