"""111

Revision ID: c2e4a6d3913c
Revises: c52eb0370d32
Create Date: 2020-11-03 19:12:36.212914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e4a6d3913c'
down_revision = 'c52eb0370d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
