"""create tables 2

Revision ID: f3e53eec9898
Revises: 05b2b099a6b3
Create Date: 2020-11-03 19:56:06.400042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e53eec9898'
down_revision = '05b2b099a6b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_spots_id'), 'spots', ['id'], unique=False)
    op.create_index(op.f('ix_spots_latitude'), 'spots', ['latitude'], unique=False)
    op.create_index(op.f('ix_spots_longitude'), 'spots', ['longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spots_longitude'), table_name='spots')
    op.drop_index(op.f('ix_spots_latitude'), table_name='spots')
    op.drop_index(op.f('ix_spots_id'), table_name='spots')
    op.drop_table('spots')
    # ### end Alembic commands ###
