version: '3.3'

services:
  proxy:
    image: traefik:v2.3
    restart: unless-stopped
    ports:
      - "80:80"
      #- "8082:8082"
    networks:
      - ext
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - --entrypoints.web.address=:80
      # general
      - --providers.docker=true
      - --api
      - --accesslog
      - --log
      - --providers.docker.constraints=Label(`traefik.constraint-label-stack`, `${TRAEFIK_TAG?Variable not set}`)
      # metrics
      - --metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000
      - --entryPoints.metrics.address=:8082
      - --metrics.prometheus.entryPoint=metrics
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addServicesLabels=true
    labels:
      - traefik.constraint-label-stack=${TRAEFIK_TAG?Variable not set}
      # dashboard
      - traefik.http.routers.traefik.rule=Host(`lb.localhost`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=admin
      - traefik.http.middlewares.admin.basicauth.users=dev:$$apr1$$d39ozBX8$$Q47EfEq9ZdD859hJuDORX.

  frontend:
    image: ${COMPOSE_PROJECT_NAME}/frontend:local
    restart: unless-stopped
    ports:
      - "7000:80"
    networks:
      - ext
    labels:
      - traefik.constraint-label-stack=${TRAEFIK_TAG?Variable not set}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-frontend.rule=Host(`localhost`)
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-frontend.loadbalancer.server.port=${FRONTEND_PORT}
    # local env
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: node_modules
    entrypoint: ["npm", "run", "start"]
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    # cater to npm needs
    environment:
      DEV_PROXY: http://placeholder:80
      PORT: 80
    stdin_open: true
    env_file:
      - ./.env.secrets

  api:
    image: ${COMPOSE_PROJECT_NAME}/api:local
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - ext
    labels:
      - traefik.constraint-label-stack=${TRAEFIK_TAG?Variable not set}
      # serve /api & strip /api
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-api.rule=Host(`localhost`) && (PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`))
      - traefik.http.middlewares.stripapi.stripprefix.prefixes=/api
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-api.middlewares=stripapi@docker
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-api.loadbalancer.server.port=${API_PORT}
    # build & live reload
    build: ./api
    entrypoint: [ "uvicorn", "app:app", "--host", "0.0.0.0", "--reload" ]
    volumes:
      - "./api:/app"

networks:
  ext:
